name: crossword_mp
description: Game media pembelajaran dan crossword game.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  word_search: ^0.1.2
  lottie: ^1.3.0
  get_cli: ^1.8.1
  bouncing_widget: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets: 
    - assets/img/
    - assets/lotties/
  uses-material-design: true


