name: crossword_mp
description: Game media pembelajaran dan crossword game.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  word_search: ^0.1.2
  lottie: ^1.3.0
  get_cli: ^1.8.1
  audioplayers: ^1.0.1
  bouncing_widget: ^2.0.0
  assets_audio_player: ^3.0.3+3 


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets: 
    - assets/img/
    - assets/lotties/
    - assets/sound/cgtss.mp3
    - assets/sound/cgt.wav
    - assets/sound/
  uses-material-design: true


